# Generated by Django 5.2.8 on 2026-04-17 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='target_email',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='target_full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='target_username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL),
        ),
    ]
