# Generated by Django 5.2.8 on 2026-04-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_onetimepassword_target_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='target_role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('admin', 'Admin'), ('superadmin', 'Superadmin')], default='viewer', max_length=20),
        ),
    ]
